"""countries: drop yellowcard_id, iso_code unique

Revision ID: 1776532d29fa
Revises: 9f89a851b00d
Create Date: 2026-07-24 18:18:44.261725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1776532d29fa'
down_revision: Union[str, None] = '9f89a851b00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_yellowcard_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=True)
    op.drop_column('countries', 'yellowcard_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('yellowcard_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=False)
    op.create_index(op.f('ix_countries_yellowcard_id'), 'countries', ['yellowcard_id'], unique=True)
    # ### end Alembic commands ###
