"""add admin invites and notifications

Revision ID: 455816a26362
Revises: 8832aea36078
Create Date: 2026-07-25 12:48:46.821191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '455816a26362'
down_revision: Union[str, None] = '8832aea36078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('category', sa.Enum('transaction', 'webhook', 'error', 'admin', 'system', name='notification_category'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', name='notification_severity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_type', sa.String(length=64), nullable=True),
    sa.Column('related_id', sa.String(length=120), nullable=True),
    sa.Column(
        'audience_min_role',
        postgresql.ENUM('super_admin', 'admin', 'viewer', name='admin_role', create_type=False),
        nullable=False,
    ),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_audience_min_role'), 'notifications', ['audience_min_role'], unique=False)
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('notification_reads',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.PrimaryKeyConstraint('notification_id', 'admin_id')
    )
    op.add_column('admin_users', sa.Column('invited_by_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'admin_users', 'admin_users', ['invited_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.drop_column('admin_users', 'invited_by_id')
    op.drop_table('notification_reads')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_audience_min_role'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
