"""add crypto_send transaction type and widen amount precision

Revision ID: 8832aea36078
Revises: ce523738a800
Create Date: 2026-07-24 20:32:45.452031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8832aea36078'
down_revision: Union[str, None] = 'ce523738a800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic ne detecte pas automatiquement les ajouts de valeur sur un ENUM
    # Postgres existant : ajoute manuellement.
    op.execute("ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'crypto_send'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
    # Note : Postgres ne permet pas de retirer une valeur d'un ENUM sans recreer
    # le type. Pas de downgrade pour la valeur 'crypto_send' (limitation Postgres).
