"""drop yellowcard_tokens, add timestamps to yellowcard_credentials

Revision ID: 9f89a851b00d
Revises: 42c3c469d4f1
Create Date: 2026-07-24 18:01:09.265367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f89a851b00d'
down_revision: Union[str, None] = '42c3c469d4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yellowcard_tokens_environment'), table_name='yellowcard_tokens')
    op.drop_table('yellowcard_tokens')
    op.add_column('yellowcard_credentials', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('yellowcard_credentials', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yellowcard_credentials', 'updated_at')
    op.drop_column('yellowcard_credentials', 'created_at')
    op.create_table('yellowcard_tokens',
    sa.Column('environment', postgresql.ENUM('sandbox', 'production', name='environment'), autoincrement=False, nullable=False),
    sa.Column('access_token_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('refreshed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('yellowcard_tokens_pkey'))
    )
    op.create_index(op.f('ix_yellowcard_tokens_environment'), 'yellowcard_tokens', ['environment'], unique=False)
    # ### end Alembic commands ###
