"""add_project_webhook_url_and_secret

Revision ID: ce33bc5a3f87
Revises: 455816a26362
Create Date: 2026-07-26 07:00:49.061731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce33bc5a3f87'
down_revision: Union[str, None] = '455816a26362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('webhook_url', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('webhook_secret_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'webhook_secret_encrypted')
    op.drop_column('projects', 'webhook_url')
    # ### end Alembic commands ###
