"""add channels table and transactions

Revision ID: ce523738a800
Revises: a31c959561dd
Create Date: 2026-07-24 19:19:29.338290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce523738a800'
down_revision: Union[str, None] = 'a31c959561dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('yellowcard_id', sa.String(length=64), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.Column('ramp_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('api_status', sa.String(length=32), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_country_id'), 'channels', ['country_id'], unique=False)
    op.create_index(op.f('ix_channels_currency_code'), 'channels', ['currency_code'], unique=False)
    op.create_index(op.f('ix_channels_ramp_type'), 'channels', ['ramp_type'], unique=False)
    op.create_index(op.f('ix_channels_status'), 'channels', ['status'], unique=False)
    op.create_index(op.f('ix_channels_yellowcard_id'), 'channels', ['yellowcard_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_yellowcard_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_status'), table_name='channels')
    op.drop_index(op.f('ix_channels_ramp_type'), table_name='channels')
    op.drop_index(op.f('ix_channels_currency_code'), table_name='channels')
    op.drop_index(op.f('ix_channels_country_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
